### ISSUE TITLE
qpzm - OracleMaker._getBasePriceWithSpread returns unfavorable price for itself.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#103] opened 2024-03-18 15:25 UTC
qpzm

high

# OracleMaker._getBasePriceWithSpread returns unfavorable price for itself.

## Summary
`OracleMaker._getBasePriceWithSpread` returns unfavorable price for itself. 

### `_getPositionRate`
`OracleMaker._getPositionRate` returns a positive value when the maker is in long position and a negative value when the maker is in short position.
It is because the return value has an opposite sign against `openNotional`.
```solidity
    int256 uncappedPositionRate = (-openNotional * 1 ether) / maxPositionNotional;
```
https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/maker/OracleMaker.sol#L476

### `reservationPrice`

`reservationPrice` has 2 cases.
It leads to the following results according to the code.
```solidity
        int256 spreadRatio = (_getOracleMakerStorage().maxSpreadRatio.toInt256() * positionRate) / 1 ether;
        uint256 reservationPrice = (basePrice * (1 ether - spreadRatio).toUint256()) / 1 ether;
```
https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/maker/OracleMaker.sol#L401-L404

#### Case1. maker's current position size > 0
1. positionRate > 0
2. spreadRatio > 0
3. reservationPrice < basePrice 

#### Case2. maker's current position size < 0
1. positionRate < 0
2. spreadRatio < 0
3. reservationPrice > basePrice

### `_getBasePriceWithSpread`
`OracleMaker._getBasePriceWithSpread` has four cases.

#### Case1. trader short & maker long 
- If maker's current position size > 0, then reservationPrice < basePrice.
  - A maker wants not to increase its long position, so it normally buys at reservationPrice which is cheaper than basePrice.
- If maker's current position size < 0, then reservationPrice > basePrice.
  - A maker wants to increase its long position, so it gives a favor to buy at reservationPrice which is higher than basePrice.

#### Case2. trader long & maker short
- If maker's current position size > 0, then reservationPrice < basePrice.
  - A maker wants to decrease its long position, so it gives a favor to sell at reservationPrice, which is lower than basePrice.
- If maker's current position size < 0, then reservationPrice > basePrice.
  - A maker wants not to increase its short position, so it normally sells at reservationPrice which is higher than basePrice.

Therefore, it is always favorable for the maker to trade at `reservationPrice` in four cases.

## POC
Add this test in [`OracleMakerFillOrderSpec` after setup function](https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/test/oracleMaker/FillOrder.spec.t.sol#L32) 
and run `forge test --mt testFuzz_fillOrder_B2Q_exactInput_Normal_om_POC`. I explain the test case in the comment.

```solidity
    function testFuzz_fillOrder_B2Q_exactInput_Normal_om_POC() public {
        // @audit Set max spread ratio to 0.1%
        maker.setMaxSpreadRatio(0.1e18);

        uint256 baseAmount = 100;

        _mockAccValue(100 ether);
        // @audit Suppose the maker already has a net short position. Set position rate = -1 ether / 100 ether = -1%.
        _mockOpenNotional(1 ether);
        vm.prank(mockClearingHouse);
        // @audit trader's short order
        (uint256 oppositeAmount, bytes memory callbackData) = maker.fillOrder(
            true, // isBaseToQuote
            true, // isExactInput
            baseAmount,
            ""
        );

        // @audit oppositeAmount should be reservationPrice, not basePrice.
        // This is the original expectedOppositeAmount in testFuzz_fillOrder_B2Q_exactInput_Normal_om.
        // uint256 expectedOppositeAmount = (baseAmount * price) / 1 ether;
        uint256 basePriceAmount = (baseAmount * price) / 1e18; // 123.45e18

        // @audit The calculation is as below.
        // maxSpreadRatio = 1e17 // 0.1%
        // int256 spreadRatio = maxSpreadRatio * positionRate / 1e18 = 1e17 * -1e16 / 1e18 = -1e15;
        // uint256 expectedOppositeAmount = 123.45e18 * (1e18 + 1e15) / 1e18 = 123.57345e18
        uint256 expectedSpreadRatio = 1e15;
        uint256 expectedOppositeAmount = basePriceAmount * (1 ether - 1e15) / 1e18;

        // @audit It should suggest a higher price to buy base token from the trader because this trade decreases the current short position.
        // basePrice * amount = 123.45e18
        // reservationPrice * amount = 123.57345e18
        // The original code fails here because it selects `FixedPointMathLib.min(basePrice, reservationPrice)` and basePrice is lower.
        assertEqDecimal(oppositeAmount, expectedOppositeAmount, 18, "fillOrder oppositeAmount mismatch");
    }

    function _mockOpenNotional(int256 openNotional) private {
        vm.mockCall(
            mockVault,
            abi.encodeWithSelector(IMarginProfile.getOpenNotional.selector, marketId, address(maker)),
            abi.encode(openNotional)
        );
    }
```

## Impact
The target position size of `OracleMaker` is 0, but the current implementation of `OracleMaker._getBasePriceWithSpread` returns a price to increase its position size.
reference: https://perp.notion.site/PythOraclePool-e99a88be051f4bc8be0b1310eb982cd4#ce111965016b46f28e25dc61d2c7c805

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/maker/OracleMaker.sol#L401-L409

## Tool used

Manual Review

## Recommendation

Update as below.

```diff
-   return
-       isBaseToQuote
-           ? FixedPointMathLib.min(basePrice, reservationPrice)
-           : FixedPointMathLib.max(basePrice, reservationPrice);
+   return reservationPrice;
```
https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/maker/OracleMaker.sol#L405-L408

**Comment by lnxrp** [comment] 2024-03-25 07:42
- Invalid
- OracleMaker's quote behavior is expected. Note it does not only depend on `reservationPrice`, but also [on the trade direction](https://github.com/perpetual-protocol/perp-contract-v3/blob/64cf71fe00c4b51a0e7215997686ff8792e4b2ee/src/maker/OracleMaker.sol#L404-L408)
- For the example case1 and case2 given above, the expected behavior and their rationale as follows:
  - Case1. trader short & maker long
    - If maker's current position size > 0
      - `reservationPrice < basePrice`
      - Trader short => `quote price = min(basePrice, reservationPrice) = reservationPrice`
      - The quoted price penalizes the trader since the trade would increase maker's existing long position
    - If maker's current position size < 0
      - `reservationPrice > basePrice`
      - Trader short => `quote price = min(basePrice, reservationPrice) = basePrice`
      - The quoted price is fair to the trader since the trade would help decrease maker's existing short position
  - Case2. trader long & maker short
    - If maker's current position size > 0
      - `reservationPrice < basePrice`
      - Trader long => `quote price = max(basePrice, reservationPrice) = basePrice`
      - The quoted price is fair to the trader since the trade would help decrease maker's existing long position
    - If maker's current position size < 0
      - `reservationPrice > basePrice`
      - Trader long => `quote price = max(basePrice, reservationPrice) = reservationPrice`
      - The quoted price penalizes the trader since the trade would increase maker's existing short position

**Comment by nevillehuang** [comment] 2024-03-27 02:34
request poc

Facilitate discussion between sponsor and watson

**Comment by sherlock-admin3** [comment] 2024-03-27 02:35
PoC requested from @qpzm

Requests remaining: **3**

**Comment by qpzm** [comment] 2024-03-27 03:16
1. I have already given a POC about Case1-2 when trader short, maker long and maker's current position size < 0 in the issue.
2. In [lnxrp's comment](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/103#issuecomment-2017396448), two parts should be fixed.

Case1-2.
When a trader goes short and a maker is in a net short position, a higher quote price is a favor for the trader because he can sell at a higher price.
```diff
Case1. trader short & maker long
If maker's current position size < 0
    reservationPrice > basePrice
-   Trader short => quote price = min(basePrice, reservationPrice) = basePrice
+   Trader short => quote price = max(basePrice, reservationPrice) = reservationPrice
```

Case2-1.
When a trader goes long and a maker is in a net long position, a lower quote price is a favor for the trader because he can buy at a lower price.
```diff
Case2. trader long & maker short 
If maker's current position size > 0
    reservationPrice < basePrice
-   Trader long => quote price = max(basePrice, reservationPrice) = basePrice
+   Trader long => quote price = min(basePrice, reservationPrice) = reservationPrice
```

**Comment by lnxrp** [comment] 2024-03-27 05:53
> Case1-2. When a trader goes short and a maker is in a net short position, a higher quote price is a favor for him because he can sell at a higher price.
> 
> ```diff
> Case1. trader short & maker long
> If maker's current position size < 0
>     reservationPrice > basePrice
> -   Trader short => quote price = min(basePrice, reservationPrice) = basePrice
> +   Trader short => quote price = max(basePrice, reservationPrice) = reservationPrice
> ```
Although a higher price favors the trader even more, it also penalizes the maker and he is more likely to sell that position at a loss. Granted, there may be situations that the maker wants to get rid of his position quick, but it should not be the norm or otherwise the maker wouldn't last long. Hence the "fair price": it is a more balanced choice that is still likely to be filled, and the maker is less likely to lose.

> Case2-1. When a trader goes long and a maker is in a net long position, a lower quote price is a favor for him because he can buy at a lower price.
> 
> ```diff
> Case2. trader long & maker short 
> If maker's current position size > 0
>     reservationPrice < basePrice
> -   Trader long => quote price = max(basePrice, reservationPrice) = basePrice
> +   Trader long => quote price = min(basePrice, reservationPrice) = reservationPrice
> ```
Similar to the reason above, we want a "fair price" more than a "good price (to the trader)".

**Closed as completed** 2024-04-02 11:30 UTC
Labels: Sponsor Disputed, Won't Fix, Non-Reward
